### PR TITLE
Added ContinueOnError flag

### PR DESCRIPTION
**Pull request by r10r**
Implements #73 .

### CODE REVIEW

**Comment by r10r** [comment]
I signed it!

**Comment by r10r** [comment]
I've added my work email to github email settings.

**Comment by hanwen** [comment]
can you follow instructions in CONTRIBUTING ? 

I usually do code reviews in Gerrit.

thanks!

**Comment by r10r** [comment]
done!

Currently tests for the change are missing - I can add them, but this will
take some time.

Btw. one test is already failing in master (without my contribution):

```
root@shieldos-dev:~/gopath/src/github.com/google/zoekt/build# go test -v .
[...]
=== RUN   TestPartialSuccess
2019/01/07 15:08:30 finished /tmp/480465520/repo_v15.00000.zoekt: 3299 index bytes (overhead 2.9)
2019/01/07 15:08:30 finished /tmp/480465520/repo_v15.00001.zoekt: 3300 index bytes (overhead 2.9)
2019/01/07 15:08:30 finished /tmp/480465520/repo_v15.00002.zoekt: 3300 index bytes (overhead 2.9)
2019/01/07 15:08:30 finished /tmp/480465520/repo_v15.00003.zoekt: 3300 index bytes (overhead 2.9)
--- FAIL: TestPartialSuccess (0.01s)
    e2e_test.go:296: got shards [/tmp/480465520/repo_v15.00000.zoekt /tmp/480465520/repo_v15.00001.zoekt /tmp/480465520/repo_v15.00002.zoekt /tmp/480465520/repo_v15.00003.zoekt], want []
```

**Pull request closed without merging**
